### ISSUE TITLE
Code on medium is exported as "big text"

### ISSUE THREAD

**Issue by ubuntudroid** [hafaio/repub#8]
When exporting code in medium articles it appears as kind of a big text in the epub instead of monospaced font. This is the case both for inline code and code blocks.

Example article: https://medium.com/proandroiddev/viewmodel-events-as-state-are-an-antipattern-35ff4fbc6fb6

# Inline code

Original:
![CleanShot 2023-11-27 at 16 56 29](https://github.com/hafaio/repub/assets/519867/651db8ef-e1bd-40be-9994-8d0821ad2c35)

ePub:
![CleanShot 2023-11-27 at 16 55 41](https://github.com/hafaio/repub/assets/519867/08f87f26-81ab-4686-941e-ecf80fc1ecda)

# Code block

Original:
![CleanShot 2023-11-27 at 16 56 17](https://github.com/hafaio/repub/assets/519867/63ad6dce-cebe-4df5-b7b7-eef280213128)

ePub (it's cut-off at the right, a soft-wrap would have been beneficial here, but that's likely another issue):
![CleanShot 2023-11-27 at 16 56 00](https://github.com/hafaio/repub/assets/519867/5383f48b-ff8f-48e4-bb0e-a9cc15d19ae7)

**Comment by erikbrinkman** [comment]
This is interesting. Offhand (and from a previous issue) it does seem like the code blocks are preserved, but the font looks more like Noto Sans, rather than Noto Mono.

Ideally I'll just have to modify the stylesheet to add that, and it should work...

If you want to to plat around, you should be able to download the raw epub from the extension. If you unzip it, you should see a stylesheet that you can edit by appening something like `pre { font-family: "Noto Mono" }`, re-zip it, and try uploading. If that works, the fix should be really easy.

I'll try to get to this soon.

**Comment by ubuntudroid** [comment]
Now that is interesting: I tried to download the ePub instead of uploading it to reMarkable and now the font is a monospaced font (I checked with the built-in macOS Books app). Soft-wrapping works as well. 🤔

So either there is different code at work in uploading vs downloading or reMarkable (I'm on a reMarkable 2 with software version 3.8.2.1965) renders the ePub differently. My screenshots from above stem from exporting the document to PDF via the reMarkable web app, but it looks exactly like on the device.

**Comment by ubuntudroid** [comment]
Okay, I tried to manually upload the ePub downloaded from the extension to my reMarkable and there it renders again as Noto Sans.

Which means the issue is that the monospace font isn't properly recognized by reMarkable for some reason and instead rendered as Noto Sans. So maybe another monospaced font needs to be used?

**Comment by erikbrinkman** [comment]
That's super bizarre... Thanks for the investigation!

**Comment by erikbrinkman** [comment]
I'm having trouble reproducing this. Either downloading directly or uploading the epub, both look like:

<img width="573" alt="Screenshot 2023-11-27 at 20 22 44" src="https://github.com/hafaio/repub/assets/858926/6a64df31-feb0-4eb6-8040-9021852ea74c">

The margins are different due to the way that uploading works from the app, but both are fixed width fonts.

I'm only checking rendering on the remarkable mac app, so maybe there's something weird if it render first on a remarkable device? I've noticed there can sometimes be changes. If I still can't find anything, maybe you can export the remarkable file for me to take a look at what might be causing the odd rendering? If that still yields no clues, I can package up a version that just inserts the font change, and have you test it to see if that fixes it.

As a side note, I tried to get word wrap working inside `pre`s, but none of the css I wrote was respected by remarkable, so I think that's SOL unless you can find some magic css that does. If you're really interested, I'd consider an option that turns on manual line wrapping, but that seems like a last resort :/

**Comment by ubuntudroid** [comment]
First, here are my settings in the Chrome extensions, just in case:
![CleanShot 2023-11-28 at 10 24 52](https://github.com/hafaio/repub/assets/519867/50c905d8-207d-4934-85d7-6d9a723682b8)

And here is a generated epub I just exported a few seconds ago (I needed to zip it as GitHub doesn't allow epub uploads): 
[Sample.epub.zip](https://github.com/hafaio/repub/files/13486073/Sample.epub.zip)

It looks like you are right that the reMarkable itself changes the epub: If I read it first in the macOS app everything is fine and a monospaced font is used. If I then open it on my reMarkable the wrong font is used there. If I then open it again in the macOS app, the wrong font will also be used there. 🤔 

Re line-breaks: it definitely would be cool to be able to have wrapping. How would you make manual wrapping to work though? Would you supply an editor for that? Or do you mean by manual "some custom code that reformats lines that are longer than a specified amount of chars"? The latter might break with different font size settings on the device, but you might be able to provide settings for that as well...

**Comment by erikbrinkman** [comment]
Okay, so it seems like just setting the font is enough, I must have just had an error in my css the first time.

This also means that wrapping is working:

<img width="492" alt="Screenshot 2023-11-28 at 21 01 02" src="https://github.com/hafaio/repub/assets/858926/c82984b5-6a82-42e4-95c4-4742af8ce2a2">

However, despite setting the text-align property, it seems that the reMarkable ignores it in favor of it's own epub alignment setting. This somewhat undoes the fixed width, as later lines get spaced apart.

Since I don't tend to render content with a lot of pre's, I have a design decision for you. I think it makes sense to throw the font change in with the default "remarkable css" since it seems like an oversight as pre's are intended to render in fixed-width font. The question is how to handle line wrapping:

1. Throw it in as well, even with justification, it's better to see the content then not
2. Make it a separate option, which means it's (maybe) unlikely to get used, if so, what default, and is this granulairty justified (I tend to lean against this becuase it's more work)
3. Just leave out wrapping all together.
4. Something I've missed, or maybe something like 2, but with the font change also thrown in as an option.

Curious to your thoughts, otherwise the fix should hopefully roll out tomorrow night.

**Comment by ubuntudroid** [comment]
Quoting you here:

> it's better to see the content then not

**So I'd go with _1_.**

_2_ sounds like a bit of over-engineering suited towards a small subset of the extension's users (then again: you already have a ton of very specific settings 😅). Might also break at any time when reMarkable changes their code, so it also might add quite a bit of maintenance efforts.

_3_ would keep things as they are and thus cut-off, correct? So not an option IMHO.

_4_ would make _2_ even more complicated to code and maintain, I wouldn't jump into that rabbit hole. 🙈

Many thanks for all your efforts with this extension, it improved my read-it-later process by 100%. 🙏

**Comment by erikbrinkman** [comment]
That's somewhat obviously how I felt, but I just wanted to make sure you didn't see things differently. Maybe you had a thought that I hadn't or saw the final result differently.

Either way, this should be fixed in v3.3.0, which is under review right now, but should be fast.

And yes there are a lot of options. I think I went overboard when I saw what remarkable allowed but didn't expose

**Comment by ubuntudroid** [comment]
> And yes there are a lot of options. I think I went overboard when I saw what remarkable allowed but didn't expose

I personally love that, but it's also a lot of maintenance effort.

Thanks for releasing that fix so quickly, much appreciated! 🙏

**Comment by ubuntudroid** [comment]
Just tested this and it works for code blocks! ❤️ 

Only gotcha I found is that the fix doesn't seem to work for inline code, there I still see that big text.

**Comment by erikbrinkman** [comment]
I *naively* assumed that inline code was just custom styling, but at least medium seems to use a `<code/>` tag, which seems reasonable to style in fixed-width. Should be a similar fix. I'll reopen until I address it.

**Comment by erikbrinkman** [comment]
Revisiting this, it not only made sense to add fixed-width font, but since on reMarkable the line-height of Noto Mono is larger than the default font, I also thought it made sense to lower the font size by 80% and add a mild light-gray background as is common for coding environments.

The results looks like this on the remarkable app. It's similar on device but with a little lower contrast.

<img width="456" alt="Screenshot 2023-11-30 at 20 14 08" src="https://github.com/hafaio/repub/assets/858926/f3dfc5a9-426a-4eba-8f3f-9f0149395d64">

<img width="456" alt="Screenshot 2023-11-30 at 20 23 09" src="https://github.com/hafaio/repub/assets/858926/955166b7-6e46-487b-80c1-fed97c871ac9">

In general, I think this makes sense, although given the magnitude of the changes, I now do think it's worth adding a setting enabling all of these called something like code-css that will be on by default.

Does this seem reasonable? Am I now going overboard?

**Comment by ubuntudroid** [comment]
This looks just great, I love it! 😍

Yes, I think a setting would be a good idea given the amount of changes to rendering this does.

**Comment by erikbrinkman** [comment]
Okay, try 3.4 😅

**Comment by ubuntudroid** [comment]
It's perfect! 🤩
